disable-version-string: True
with-expecter: True
filename: "{{.InterfaceName}}Mock.go"
mockname: "{{.InterfaceName}}Mock"
packages:
  github.com/sesaquecruz/go-payment-processor/internal/application/repository:
    config:
      all: True
      dir: "mocks/application/repository"
      outpkg: "repository"
  github.com/sesaquecruz/go-payment-processor/internal/application/service:
    config:
      all: True
      dir: "mocks/application/service"
      outpkg: "service"
  github.com/sesaquecruz/go-payment-processor/internal/application/usecase:
    config:
      all: True
      dir: "mocks/application/usecase"
      outpkg: "usecase"
