disable-version-string: True
with-expecter: True
filename: "{{.InterfaceName}}Mock.go"
mockname: "{{.InterfaceName}}Mock"
packages:
  github.com/sesaquecruz/go-payment-processor/internal/core/repository:
    config:
      all: True
      dir: "test/mocks/core/repository"
      outpkg: "repository"
  github.com/sesaquecruz/go-payment-processor/internal/core/service:
    config:
      all: True
      dir: "test/mocks/core/service"
      outpkg: "service"
  github.com/sesaquecruz/go-payment-processor/internal/core/usecase:
    config:
      all: True
      dir: "test/mocks/core/usecase"
      outpkg: "usecase"
  github.com/sesaquecruz/go-payment-processor/internal/acquirer:
    config:
      all: True
      dir: "test/mocks/acquirer"
      outpkg: "acquirer"
  github.com/sesaquecruz/go-payment-processor/internal/infra/web/handler:
    config:
      all: True
      dir: "test/mocks/infra/web/handler"
      outpkg: "handler"
