version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: ppapp
      POSTGRES_PASSWORD: ppapp123
      POSTGRES_DB: ppdb
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready
      timeout: 10s
      retries: 6

  migrate:
    container_name: migrate
    depends_on:
      postgres:
        condition: service_healthy
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations:ro
    command: [ "-path", "/migrations", "-database",  "postgres://ppapp:ppapp123@postgres:5432/ppdb?sslmode=disable", "-verbose", "up" ]

  acquirer:
    container_name: acquirer
    build:
      context: .
      dockerfile: ./test/acquirer/cmd/Dockerfile
    image: go-acquirer:latest
    ports:
      - "6061:6061"
