version: '3.8'

services:
  acquirer:
    container_name: acquirer
    build:
      context: .
      dockerfile: ./test/acquirer/cmd/Dockerfile
    image: go-acquirer:local-compose
    ports:
      - "6061:6061"

  postgres:
    container_name: postgres
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: ppapp
      POSTGRES_PASSWORD: ppapp123
      POSTGRES_DB: ppdb
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready
      timeout: 10s
      retries: 6

  sql-seed:
    container_name: sql-seed
    image: ghcr.io/sesaquecruz/go-sql-seed:release-1.0.0
    volumes:
      - ./migrations:/migrations:ro
      - ./.docker/test-data:/data:ro
    environment:
      - MIGRATIONS_PATH=/migrations
      - DATA_PATH=/data
      - DB_DRIVER=postgres
      - DB_DSN=ppapp:ppapp123@postgres:5432/ppdb?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

  payment-processor:
    container_name: payment-processor
    build:
      context: .
    image: payment-processor:local-compose
    environment:
      DB_DSN: ppapp:ppapp123@postgres:5432/ppdb?sslmode=disable
      CIELO_URL: http://acquirer:6061/cielo
      REDE_URL: http://acquirer:6061/rede
      STONE_URL: http://acquirer:6061/stone
      CIELO_KEY: cielo-api-key
      REDE_KEY: rede-api-key
      STONE_KEY: stone-api-key
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
