// Code generated by mockery. DO NOT EDIT.

package service

import (
	context "context"

	entity "github.com/sesaquecruz/go-payment-processor/internal/core/entity"
	mock "github.com/stretchr/testify/mock"
)

// PaymentServiceMock is an autogenerated mock type for the PaymentService type
type PaymentServiceMock struct {
	mock.Mock
}

type PaymentServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentServiceMock) EXPECT() *PaymentServiceMock_Expecter {
	return &PaymentServiceMock_Expecter{mock: &_m.Mock}
}

// ProcessTransaction provides a mock function with given fields: ctx, transaction
func (_m *PaymentServiceMock) ProcessTransaction(ctx context.Context, transaction *entity.Transaction) (*entity.Payment, error) {
	ret := _m.Called(ctx, transaction)

	var r0 *entity.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Transaction) (*entity.Payment, error)); ok {
		return rf(ctx, transaction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Transaction) *entity.Payment); ok {
		r0 = rf(ctx, transaction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.Transaction) error); ok {
		r1 = rf(ctx, transaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentServiceMock_ProcessTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessTransaction'
type PaymentServiceMock_ProcessTransaction_Call struct {
	*mock.Call
}

// ProcessTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - transaction *entity.Transaction
func (_e *PaymentServiceMock_Expecter) ProcessTransaction(ctx interface{}, transaction interface{}) *PaymentServiceMock_ProcessTransaction_Call {
	return &PaymentServiceMock_ProcessTransaction_Call{Call: _e.mock.On("ProcessTransaction", ctx, transaction)}
}

func (_c *PaymentServiceMock_ProcessTransaction_Call) Run(run func(ctx context.Context, transaction *entity.Transaction)) *PaymentServiceMock_ProcessTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Transaction))
	})
	return _c
}

func (_c *PaymentServiceMock_ProcessTransaction_Call) Return(_a0 *entity.Payment, _a1 error) *PaymentServiceMock_ProcessTransaction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PaymentServiceMock_ProcessTransaction_Call) RunAndReturn(run func(context.Context, *entity.Transaction) (*entity.Payment, error)) *PaymentServiceMock_ProcessTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentServiceMock creates a new instance of PaymentServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentServiceMock {
	mock := &PaymentServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
