// Code generated by mockery. DO NOT EDIT.

package repository

import (
	context "context"

	entity "github.com/sesaquecruz/go-payment-processor/internal/core/entity"
	mock "github.com/stretchr/testify/mock"
)

// ICardRepositoryMock is an autogenerated mock type for the ICardRepository type
type ICardRepositoryMock struct {
	mock.Mock
}

type ICardRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ICardRepositoryMock) EXPECT() *ICardRepositoryMock_Expecter {
	return &ICardRepositoryMock_Expecter{mock: &_m.Mock}
}

// FindCard provides a mock function with given fields: ctx, cardToken
func (_m *ICardRepositoryMock) FindCard(ctx context.Context, cardToken string) (*entity.Card, error) {
	ret := _m.Called(ctx, cardToken)

	var r0 *entity.Card
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.Card, error)); ok {
		return rf(ctx, cardToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Card); ok {
		r0 = rf(ctx, cardToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Card)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cardToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ICardRepositoryMock_FindCard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCard'
type ICardRepositoryMock_FindCard_Call struct {
	*mock.Call
}

// FindCard is a helper method to define mock.On call
//   - ctx context.Context
//   - cardToken string
func (_e *ICardRepositoryMock_Expecter) FindCard(ctx interface{}, cardToken interface{}) *ICardRepositoryMock_FindCard_Call {
	return &ICardRepositoryMock_FindCard_Call{Call: _e.mock.On("FindCard", ctx, cardToken)}
}

func (_c *ICardRepositoryMock_FindCard_Call) Run(run func(ctx context.Context, cardToken string)) *ICardRepositoryMock_FindCard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ICardRepositoryMock_FindCard_Call) Return(_a0 *entity.Card, _a1 error) *ICardRepositoryMock_FindCard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ICardRepositoryMock_FindCard_Call) RunAndReturn(run func(context.Context, string) (*entity.Card, error)) *ICardRepositoryMock_FindCard_Call {
	_c.Call.Return(run)
	return _c
}

// NewICardRepositoryMock creates a new instance of ICardRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICardRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICardRepositoryMock {
	mock := &ICardRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
